// <auto-generated />
using Ingestion.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ingestion.Migrations
{
    [DbContext(typeof(GtfsDbContext))]
    [Migration("20261005102636_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ingestion.Data.Route", b =>
                {
                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("LongName")
                        .HasColumnType("text")
                        .HasColumnName("long_name");

                    b.Property<int>("RouteType")
                        .HasColumnType("integer")
                        .HasColumnName("route_type");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.HasKey("RouteId");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("Ingestion.Data.Stop", b =>
                {
                    b.Property<string>("StopId")
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("StopId");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("Ingestion.Data.StopTime", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<int?>("ArrivalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("arrival_seconds");

                    b.Property<int?>("DepartureSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("departure_seconds");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.HasKey("TripId", "StopSequence");

                    b.HasIndex("StopId");

                    b.ToTable("stop_times", (string)null);
                });

            modelBuilder.Entity("Ingestion.Data.Trip", b =>
                {
                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<string>("Headsign")
                        .HasColumnType("text")
                        .HasColumnName("headsign");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("TripId");

                    b.HasIndex("RouteId");

                    b.ToTable("trips", (string)null);
                });

            modelBuilder.Entity("Ingestion.Data.StopTime", b =>
                {
                    b.HasOne("Ingestion.Data.Trip", null)
                        .WithMany()
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ingestion.Data.Trip", b =>
                {
                    b.HasOne("Ingestion.Data.Route", null)
                        .WithMany()
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
